### ISSUE TITLE
Does schedule.json get updated?

### ISSUE THREAD

**Issue by reaganking** [EvRoHa/SP-plus-Visualizations#5]
I'm trying to use your JSON schedule but I'm getting mostly TBA for startTime for games this week (2018-09-22).

**Comment by EvRoHa** [comment]
Yes, I update the JSON file about twice each week. That's done by scraping the NCAA schedule from their website and updating fields as they become populated. If you look in 'schedule.py' you'll see a method for updating from the NCAA. The last three lines in that file make a quick schedule object, update the data in it, then overwrite the file. You can run this whenever you like to update the schedule file. Hope that helps.

**Comment by reaganking** [comment]
Thanks, Evan. Appreciate the response. I was trying to update it but wasn't having much luck for some reason (new to all of this). Will give it another shot.
