### ISSUE TITLE
ND did not lose to Navy

### ISSUE THREAD

**Issue by CleverScreenName** [EvRoHa/SP-plus-Visualizations#6]
ND did not lose to Navy, so the "notre dame - sp+ - red-green" chart is in error right now.

**Comment by EvRoHa** [comment]
As documented elsewhere, it's an on-going issue with the NCAA db not being correctly updated. When the routine automatically updates my local db, this causes several games to be incorrectly reported. I resolved it by adding a field to the games that were being effected that precludes them from being updated. I'll still have to manually detect which games are being incorrectly reported, but once I do and label them as "doNotUpdate" that should prevent the issue from recurring.

**Comment by CleverScreenName** [comment]
Evan,

Sorry to be one of the whiny Notre Dame fans, but, well, it worked, didn’t it?

Any chance of getting copies of the Notre Dame “Total Projected Wins as per SP+” charts from before Week 5?

Thanks,
Robert
